version: '3.8'
services:
  postgres-inventory:
    image: postgres:13
    container_name: postgres-inventory
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: inventory
    volumes:
      - postgres-inventory-data:/var/lib/postgresql/data

volumes:
  postgres-inventory-data: 